export let restaurants = [
  {
    info: {
      id: "36358",
      name: "Pizza Hut",
      cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
      locality: "Baani Square",
      areaName: "Sector 50",
      costForTwo: "₹350 for two",
      cuisines: ["Pizzas"],
      avgRating: 3.9,
      parentId: "721",
      avgRatingString: "3.9",
      totalRatingsString: "1K+",
    },
  },
  {
    info: {
      id: "50463",
      name: "Burger King",
      cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
      locality: "Element One Mall",
      areaName: "Sector 47",
      costForTwo: "₹350 for two",
      cuisines: ["Burgers", "American"],
      avgRating: 4.3,
      parentId: "166",
      avgRatingString: "4.3",
      totalRatingsString: "10K+",

      deliveryTime: 24,
      lastMileTravel: 1.8,
      serviceability: "SERVICEABLE",
      slaString: "20-25 mins",
      lastMileTravelString: "1.8 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    info: {
      id: "183843",
      name: "Starbucks Coffee",
      cloudinaryImageId: "258fe8a3577877fbfe064095ed1d9dc3",
      locality: "Element One Mall",
      areaName: "Sector 49",
      costForTwo: "₹400 for two",
      cuisines: [
        "Beverages",
        "Cafe",
        "Snacks",
        "Desserts",
        "Bakery",
        "Ice Cream",
      ],
      avgRating: 4.1,
      parentId: "195515",
      avgRatingString: "4.1",
      totalRatingsString: "1K+",
    },
  },
  {
    info: {
      id: "39243",
      name: "KFC",
      cloudinaryImageId: "f01666ac73626461d7455d9c24005cd4",
      locality: "ILD Mall",
      areaName: "Sohna Road",
      costForTwo: "₹450 for two",
      cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
      avgRating: 4.1,
      parentId: "547",
      avgRatingString: "4.1",
      totalRatingsString: "10K+",
    },
  },
  {
    info: {
      id: "254107",
      name: "McDonald's",
      cloudinaryImageId: "6dc3ed2ca21d71acff7c2a51dfe4c720",
      locality: "Eros City Square Mall",
      areaName: "Sector 49",
      costForTwo: "₹400 for two",
      cuisines: ["American"],
      avgRating: 4.3,
      parentId: "630",
      avgRatingString: "4.3",
      totalRatingsString: "10K+",
    },
  },
  {
    info: {
      id: "24215",
      name: "Domino's Pizza",
      cloudinaryImageId: "nsvnvjoqicjxr0ohgspf",
      locality: "Sector 49",
      areaName: "Sohna Road",
      costForTwo: "₹400 for two",
      cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
      avgRating: 4.2,
      parentId: "2456",
      avgRatingString: "4.2",
      totalRatingsString: "10K+",
    },
  },
  {
    info: {
      id: "332226",
      name: "Tossin Pizza",
      cloudinaryImageId: "313485a665bd0f4958fdc14ead8afade",
      locality: "Sector 50",
      areaName: "Sector 50",
      costForTwo: "₹600 for two",
      cuisines: ["Pizzas", "Italian", "Beverages", "Desserts"],
      avgRating: 4.4,
      parentId: "1778",
      avgRatingString: "4.4",
      totalRatingsString: "1K+",
    },
  },

  {
    info: {
      id: "296838",
      name: "Thalairaj Biryani",
      cloudinaryImageId: "dspgvwisdm6cqo7bv7xd",
      locality: "Sector 49",
      areaName: "Sohna Road",
      costForTwo: "₹300 for two",
      cuisines: [
        "Andhra",
        "Biryani",
        "Hyderabadi",
        "South Indian",
        "Indian",
        "Beverages",
      ],
      avgRating: 4.5,
      parentId: "433875",
      avgRatingString: "4.5",
      totalRatingsString: "1K+",
    },
  },
  {
    info: {
      id: "36509",
      name: "Tibb's Frankie - Serving Rolls Since 1969",
      cloudinaryImageId: "agkneu9bkxlbhvovfiry",
      locality: "Baani Square",
      areaName: "Sector 50",
      costForTwo: "₹200 for two",
      cuisines: ["Rolls & Wraps", "Fast Food"],
      avgRating: 4,
      parentId: "472083",
      avgRatingString: "4.0",
      totalRatingsString: "1K+",
    },
  },
  {
    info: {
      id: "20140",
      name: "Subway",
      cloudinaryImageId: "1ace5fa65eff3e1223feb696c956b38b",
      locality: "Good Earth City Centre",
      areaName: "Sector 50",
      costForTwo: "₹350 for two",
      cuisines: ["Salads", "Snacks", "Desserts", "Beverages"],
      avgRating: 4.6,
      parentId: "2",
      avgRatingString: "4.6",
      totalRatingsString: "10K+",
    },
  },
  {
    info: {
      id: "61324",
      name: "Dana Choga",
      cloudinaryImageId: "dye74amxjfmdrjuz8wug",
      locality: "Sector 50",
      areaName: "Sector 50",
      costForTwo: "₹800 for two",
      cuisines: [
        "North Indian",
        "Indian",
        "Mughlai",
        "Chinese",
        "Biryani",
        "Beverages",
        "Desserts",
      ],
      avgRating: 4.4,
      parentId: "5179",
      avgRatingString: "4.4",
      totalRatingsString: "10K+",
    },
  },
  {
    info: {
      id: "75898",
      name: "Salad Days",
      cloudinaryImageId: "cfa1123ebf17413dc7d0a80c7361fab3",
      locality: "M3M TEE POINT",
      areaName: "Sector 66",
      costForTwo: "₹500 for two",
      cuisines: ["Salads"],
      avgRating: 4.6,
      parentId: "796",
      avgRatingString: "4.6",
      totalRatingsString: "5K+",
    },
  },
  {
    info: {
      id: "304634",
      name: "Caterspoint",
      cloudinaryImageId: "qs4botldnfxbx9lrxdqx",
      locality: "Village Samaspur",
      areaName: "Sector 50",
      costForTwo: "₹600 for two",
      cuisines: ["Healthy Food", "Italian", "Salads"],
      avgRating: 4.4,
      parentId: "11011",
      avgRatingString: "4.4",
      totalRatingsString: "5K+",
    },
  },
  {
    info: {
      id: "304640",
      name: "Saladspoint",
      cloudinaryImageId: "6116a2736e177c4a872d11a9d077584a",
      locality: "Village Samaspur",
      areaName: "Sector 50",
      costForTwo: "₹600 for two",
      cuisines: ["Salads"],
      avgRating: 4.5,
      parentId: "8786",
      avgRatingString: "4.5",
      totalRatingsString: "1K+",
    },
  },

  {
    info: {
      id: "468763",
      name: "Burgerama",
      cloudinaryImageId: "1d52387b37dbec1712d0142aec3421a6",
      locality: "Sohna Road",
      areaName: "Sector 49",
      costForTwo: "₹600 for two",
      cuisines: ["American"],
      avgRating: 4.3,
      parentId: "8993",
      avgRatingString: "4.3",
      totalRatingsString: "1K+",
    },
  },
  {
    info: {
      id: "275516",
      name: "Chinese Daily",
      cloudinaryImageId: "fcdc89cb181db991b3db418c53d3e585",
      locality: "Baani Square",
      areaName: "Sector 50",
      costForTwo: "₹500 for two",
      cuisines: ["Pan-Asian", "Chinese", "Thai", "Seafood", "Oriental"],
      avgRating: 4.2,
      parentId: "9712",
      avgRatingString: "4.2",
      totalRatingsString: "1K+",
    },
  },
  {
    info: {
      id: "50748",
      name: "Sandburgs",
      cloudinaryImageId: "npcw95xz9iwhlbjumoon",
      locality: "Baani Square",
      areaName: "Sector 50",
      costForTwo: "₹500 for two",
      cuisines: ["Burgers", "American", "Pastas", "Salads"],
      avgRating: 4.4,
      parentId: "446963",
      avgRatingString: "4.4",
      totalRatingsString: "10K+",
    },
  },
  {
    info: {
      id: "159270",
      name: "Lo! - Low Carb and Keto Foods",
      cloudinaryImageId: "ltrwqgjxwhh3rfsy4gf2",
      locality: "JP MARKET",
      areaName: "SAMASPUR",
      costForTwo: "₹100 for two",
      cuisines: ["Healthy Food", "Keto", "Continental"],
      avgRating: 4.2,
      parentId: "8282",
      avgRatingString: "4.2",
      totalRatingsString: "1K+",
    },
  },

  {
    info: {
      id: "6488",
      name: "Chaayos Chai+Snacks=Relax",
      cloudinaryImageId: "cace805a6ba74137571d0f7ac92302b1",
      locality: "Good Earth City Centre",
      areaName: "Sector 50",
      costForTwo: "₹250 for two",
      cuisines: [
        "Bakery",
        "Beverages",
        "Chaat",
        "Desserts",
        "Home Food",
        "Italian",
        "Maharashtrian",
        "Snacks",
        "Street Food",
        "Sweets",
      ],
      avgRating: 4.4,
      parentId: "281782",
      avgRatingString: "4.4",
      totalRatingsString: "10K+",

      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
    },
  },
  {
    info: {
      id: "501341",
      name: "Nomad Pizza- Traveller Series",
      cloudinaryImageId: "a14f952df15d37ac5017519beab18683",
      locality: "Gurugram",
      areaName: "Baani Square",
      costForTwo: "₹700 for two",
      cuisines: ["Pizzas", "Fast Food", "Desserts", "Beverages"],
      avgRating: 4.3,
      parentId: "251919",
      avgRatingString: "4.3",
      totalRatingsString: "500+",
    },
  },
];
