export let restaurants = [
  {
    info: {
      id: "39243",
      name: "KFC",
      cloudinaryImageId: "f01666ac73626461d7455d9c24005cd4",
      locality: "ILD Mall",
      areaName: "Sohna Road",
      costForTwo: "₹450 for two",
      cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
      avgRating: 4.1,
      parentId: "547",
      avgRatingString: "4.1",
      totalRatingsString: "10K+",
    },
  },
  {
    info: {
      id: "50463",
      name: "Burger King",
      cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
      locality: "Element One Mall",
      areaName: "Sector 47",
      costForTwo: "₹350 for two",
      cuisines: ["Burgers", "American"],
      avgRating: 4.3,
      parentId: "166",
      avgRatingString: "4.3",
      totalRatingsString: "10K+",
    },
  },
  {
    info: {
      id: "254107",
      name: "McDonald's",
      cloudinaryImageId: "6dc3ed2ca21d71acff7c2a51dfe4c720",
      locality: "Eros City Square Mall",
      areaName: "Sector 49",
      costForTwo: "₹400 for two",
      cuisines: ["American"],
      avgRating: 4.3,
      parentId: "630",
      avgRatingString: "4.3",
      totalRatingsString: "10K+",
    },
  },
  {
    info: {
      id: "24215",
      name: "Domino's Pizza",
      cloudinaryImageId: "nsvnvjoqicjxr0ohgspf",
      locality: "Sector 49",
      areaName: "Sohna Road",
      costForTwo: "₹400 for two",
      cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
      avgRating: 4.2,
      parentId: "2456",
      avgRatingString: "4.2",
      totalRatingsString: "10K+",
    },
  },
  {
    info: {
      id: "8897",
      name: "Coastal Reef",
      cloudinaryImageId: "oc7m59hybgylsh6s55ff",
      locality: "Baani Square",
      areaName: "Sector 50",
      costForTwo: "₹600 for two",
      cuisines: ["Indian", "Coastal"],
      avgRating: 4.4,
      parentId: "2413",
      avgRatingString: "4.4",
      totalRatingsString: "5K+",
    },
  },
  {
    info: {
      id: "31097",
      name: "Southern Junction",
      cloudinaryImageId: "czdmaxo1yhbku5hgqs8r",
      locality: "Baani Square",
      areaName: "Sector 50",
      costForTwo: "₹250 for two",
      cuisines: ["South Indian"],
      avgRating: 4,
      parentId: "5357",
      avgRatingString: "4.0",
      totalRatingsString: "10K+",
    },
  },
  {
    info: {
      id: "296838",
      name: "Thalairaj Biryani",
      cloudinaryImageId: "dspgvwisdm6cqo7bv7xd",
      locality: "Sector 49",
      areaName: "Sohna Road",
      costForTwo: "₹300 for two",
      cuisines: [
        "Andhra",
        "Biryani",
        "Hyderabadi",
        "South Indian",
        "Indian",
        "Beverages",
      ],
      avgRating: 4.5,
      parentId: "433875",
      avgRatingString: "4.5",
      totalRatingsString: "1K+",
    },
  },
  {
    info: {
      id: "36358",
      name: "Pizza Hut",
      cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
      locality: "Baani Square",
      areaName: "Sector 50",
      costForTwo: "₹350 for two",
      cuisines: ["Pizzas"],
      avgRating: 3.9,
      parentId: "721",
      avgRatingString: "3.9",
      totalRatingsString: "1K+",
    },
  },
  {
    info: {
      id: "61324",
      name: "Dana Choga",
      cloudinaryImageId: "dye74amxjfmdrjuz8wug",
      locality: "Sector 50",
      areaName: "Sector 50",
      costForTwo: "₹800 for two",
      cuisines: [
        "North Indian",
        "Indian",
        "Mughlai",
        "Chinese",
        "Biryani",
        "Beverages",
        "Desserts",
      ],
      avgRating: 4.4,
      parentId: "5179",
      avgRatingString: "4.4",
      totalRatingsString: "10K+",
    },
  },
  {
    info: {
      id: "75898",
      name: "Salad Days",
      cloudinaryImageId: "cfa1123ebf17413dc7d0a80c7361fab3",
      locality: "M3M TEE POINT",
      areaName: "Sector 66",
      costForTwo: "₹500 for two",
      cuisines: ["Salads"],
      avgRating: 4.6,
      parentId: "796",
      avgRatingString: "4.6",
      totalRatingsString: "5K+",
    },
  },
];
